export const FETCH_PROBLEMS_STARTED = 'PROBLEM_LIST/FETCH_PROBLEMS_STARTED';
export const FETCH_PROBLEMS_SUCCESS = 'PROBLEM_LIST/FETCH_PROBLEMS_SUCCESS';
export const FETCH_PROBLEMS_FAILURE = 'PROBLEM_LIST/FETCH_PROBLEMS_FAILURE';
export const CHANGE_PAGE_TO = 'PROBLEM_LIST/CHANGE_PAGE_TO';
export const SET_TOTAL_PROBLEM_NUMBER = 'PROBLEM_LIST/SET_TOTAL_PROBLEM_NUMBER';
