export const FETCH_PROBLEMS_STARTED = 'PROBLEMLIST/FETCH_PROBLEMS_STARTED';
export const FETCH_PROBLEMS_SUCCESS = 'PROBLEMLIST/FETCH_PROBLEMS_SUCCESS';
export const FETCH_PROBLEMS_FAILURE = 'PROBLEMLIST/FETCH_PROBLEMS_FAILURE';