export const GET_PROBLEM_AT_PAGE = 'GET_PROBLEM_AT_PAGE';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';
export const GET_SUBMIT_BY_ID = 'GET_SUBMIT_BY_ID';
export const GET_ME = 'GET_ME';
export const GET_PROBLEM_BY_ID = 'GET_PROBLEM_BY_ID';
export const POST_SUBMIT_TO_PROBLEM = 'POST_SUBMIT_TO_PROBLEM';
export const GET_SUBMITS_BY_PROBLEM_ID = 'GET_SUBMITS_BY_PROBLEM_ID';