export const FETCH_PROBLEM_DESC_LOADING = 'PROBLEMDESC/FETCH_PROBLEM_DESC_LOADING';
export const FETCH_PROBLEM_DESC_SUCCESS = 'PROBLEMDESC/FETCH_PROBLEM_DESC_SUCCESS';
export const FETCH_PROBLEM_DESC_FAILURE = 'PROBLEMDESC/FETCH_PROBLEM_DESC_FAILURE';